#!/usr/bin/env python
# -*- coding: utf-8 -*-
import smtplib
from patchmate.helpers.logger import logger


BODY = """From: {sender_email}
To: {receivers}
CC: {cc_list}
Subject: SUBJECT

CONTENT
"""

class EmailSender(object):
    def __init__(self, login, password, smtp_server, sender, receivers, cc_list):
        self.sender = sender
        self.receivers = receivers
        self.smtp_obj = smtplib.SMTP_SSL(smtp_server)
        self.smtp_obj.login(login, password)
        self.cc_list = cc_list

    def send_notification(self):
        try:
            self.smtp_obj.sendmail(self.sender, self.receivers, BODY.format(sender_email=self.sender,
                                                                            receivers=', '.join(self.receivers),
                                                                            cc_list=', '.join(self.cc_list)))
            logger.info("Successfully sent email")
        except smtplib.SMTPException as e:
            logger.error(e)
